PUBLIC VerCar1 ;Vertical car1
EXTRN Car1Position:BYTE

.MODEL SMALL
.CODE
VerCar1 PROC FAR

LEA SI,Car1Position+8   ; ASSIGN THE ADDRESS OF THE HEX COLOR OF THE IMAGE TO SI

MOV BH,0
MOV CX,word ptr Car1Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV DX,word ptr Car1Position+4   ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
BACK:
MOV AH,0DH
INT 10H
MOV [SI+540],AL
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H     ;Draw PixeL
INC CX      ;MOVE ON PIXEL ON X AXIS
INC SI      ;MOVE TO THE NEXT PIXEL COLOR
CMP CX,word ptr Car1Position+2  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ BACK
MOV CX,WORD PTR Car1Position    ;RETURN TO THE BEGINNING POSITION ON X AXIS
DEC DX
CMP DX,WORD PTR Car1Position+6  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ BACK

RET
VerCar1 ENDP
END VerCar1