EXTRN Car1Position:BYTE
EXTRN Car2Position:BYTE
EXTRN State1:BYTE
EXTRN State2:BYTE
PUBLIC Car1 
PUBLIC Car2 

.MODEL SMALL
.CODE
Car1 PROC FAR

MOV AX, 0A000H
MOV ES, AX

LEA SI,Car1Position+8   ; ASSIGN THE ADDRESS OF THE HEX COLOR OF THE IMAGE TO SI
MOV BH,0
MOV AX,WORD ptr State1
;;;;;;;;;;;;
MOV CX,word ptr Car1Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV DX,word ptr Car1Position+4   ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
CMP AX,0101H
JZ Front
;;;;;;;;;;;;;;;
MOV CX,word ptr Car1Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV DX,word ptr Car1Position+6   ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
CMP AX,0001H
JZ BACK_HELP
;;;;;;;;;;;;;;;;;;;;
MOV DX,word ptr Car1Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV CX,word ptr Car1Position+6   ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
CMP AX,0100H
JZ Right
;;;;;;;;;;;;;;;;;;;;;;;;
MOV DX,word ptr Car1Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV CX,word ptr Car1Position+4   ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
CMP AX,0000H
JZ LEFT_HELP
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Right:
MOV AH,0DH
INT 10H
MOV [SI+540],AL
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H
INC DX      ;MOVE ON PIXEL ON X AXIS
INC SI      ;MOVE TO THE NEXT PIXEL COLOR
CMP DX,word ptr Car1Position+2  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ Right
MOV DX,WORD PTR Car1Position    ;RETURN TO THE BEGINNING POSITION ON X AXIS
INC CX
CMP CX,WORD PTR Car1Position+4  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ Right
JMP EXIT

BACK_HELP:
JMP BACK
;;;;;;;;;;;;;;;;;;;;;;;;;;;
Front:
MOV AH,0DH
INT 10H
MOV [SI+540],AL
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H
INC CX      ;MOVE ON PIXEL ON X AXIS
INC SI      ;MOVE TO THE NEXT PIXEL COLOR
CMP CX,word ptr Car1Position+2  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ Front
MOV CX,WORD PTR Car1Position    ;RETURN TO THE BEGINNING POSITION ON X AXIS
DEC DX
CMP DX,WORD PTR Car1Position+6  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ Front
JMP EXIT
;;;;;;;;;;;;;;;;;;;

LEFT_HELP:
JMP LEFT

Back:
MOV AH,0DH
INT 10H
MOV [SI+540],AL
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H
INC CX      ;MOVE ON PIXEL ON X AXIS
INC SI      ;MOVE TO THE NEXT PIXEL COLOR
CMP CX,word ptr Car1Position+2  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ Back
MOV CX,WORD PTR Car1Position    ;RETURN TO THE BEGINNING POSITION ON X AXIS
INC DX
CMP DX,WORD PTR Car1Position+4  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ Back
JMP EXIT


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;
Left:
MOV AH,0DH
INT 10H
MOV [SI+540],AL
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10h
INC DX      ;MOVE ON PIXEL ON X AXIS
INC SI      ;MOVE TO THE NEXT PIXEL COLOR
CMP DX,word ptr Car1Position+2  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ Left
MOV DX,WORD PTR Car1Position    ;RETURN TO THE BEGINNING POSITION ON X AXIS
DEC CX
CMP CX,WORD PTR Car1Position+6  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ Left
JMP EXIT
EXIT:
RET
Car1 ENDP


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


Car2 PROC FAR
LEA SI,Car2Position+8   ; ASSIGN THE ADDRESS OF THE HEX COLOR OF THE IMAGE TO SI

MOV CX,word ptr Car2Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV DX,word ptr Car2Position+4  ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR
BACK2:
MOV AH,0DH
INT 10H
MOV [SI+540],AL
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H             ;Draw PixeL
INC CX              ;MOVE ON PIXEL ON X AXIS
INC SI              ;MOVE TO THE NEXT PIXEL COLOR
CMP CX,word ptr Car2Position+2      ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ BACK2
MOV CX,WORD PTR Car2Position        ;RETURN TO THE BEGINNING POSITION ON X AXIS
DEC DX
CMP DX,WORD PTR Car2Position+6      ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ BACK2

RET
Car2 ENDP
END Car1