EXTRN Car1Position:BYTE
EXTRN State1:BYTE
EXTRN OrigPixel1:BYTE
PUBLIC RESETCAR1
.MODEL SMALL
.CODE
RESETCAR1 PROC FAR

LEA SI,OrigPixel1   ; ASSIGN THE ADDRESS OF THE HEX COLOR OF THE IMAGE TO SI
MOV BH,0
MOV AX,WORD ptr State1
;;;;;;;;;;;;
MOV CX,word ptr Car1Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV DX,word ptr Car1Position+4   ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
CMP AX,0101H
JZ Front2
;;;;;;;;;;;;;;;
MOV CX,word ptr Car1Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV DX,word ptr Car1Position+6   ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
CMP AX,0001H
JZ BACK2
;;;;;;;;;;;;;;;;;;;;
MOV DX,word ptr Car1Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV CX,word ptr Car1Position+6   ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
CMP AX,0100H
JZ Right2
;;;;;;;;;;;;;;;;;;;;;;;;
MOV DX,word ptr Car1Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV CX,word ptr Car1Position+4  ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
CMP AX,0H
JZ Left2
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Right2:
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H       ;Draw PixeL
INC DX        ;MOVE ON PIXEL ON X AXIS
INC SI        ;MOVE TO THE NEXT PIXEL COLOR
CMP DX,word ptr Car1Position+2  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ Right2
MOV DX,WORD PTR Car1Position    ;RETURN TO THE BEGINNING POSITION ON X AXIS
INC CX
CMP CX,WORD PTR Car1Position+4  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ Right2
JMP EXITT
;;;;;;;;;;;;;;;
Front2:
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H     ;Draw PixeL
INC CX      ;MOVE ON PIXEL ON X AXIS
INC SI      ;MOVE TO THE NEXT PIXEL COLOR
CMP CX,word ptr Car1Position+2  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ Front2
MOV CX,WORD PTR Car1Position    ;RETURN TO THE BEGINNING POSITION ON X AXIS
DEC DX
CMP DX,WORD PTR Car1Position+6  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ Front2
JMP EXITT
;;;;;;;;;;;;;;;;;;;



Back2:
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H     ;Draw PixeL
INC CX      ;MOVE ON PIXEL ON X AXIS
INC SI      ;MOVE TO THE NEXT PIXEL COLOR
CMP CX,word ptr Car1Position+2  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ BACK2
MOV CX,WORD PTR Car1Position    ;RETURN TO THE BEGINNING POSITION ON X AXIS
INC DX
CMP DX,WORD PTR Car1Position+4  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ Back2
JMP EXITT
EXITT:JMP EXIT2
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;
Left2:
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H     ;Draw PixeL
INC DX      ;MOVE ON PIXEL ON X AXIS
INC SI      ;MOVE TO THE NEXT PIXEL COLOR
CMP DX,word ptr Car1Position+2  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ Left2
MOV DX,WORD PTR Car1Position    ;RETURN TO THE BEGINNING POSITION ON X AXIS
DEC CX
CMP CX,WORD PTR Car1Position+6  ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ Left2
JMP EXIT2
EXIT2:
RET
RESETCAR1 ENDP
END RESETCAR1
