PUBLIC VerCar2 ;Vertical Car2
EXTRN Car2Position:BYTE

.MODEL SMALL
.CODE
VerCar2 PROC FAR
LEA SI,Car2Position+8   ; ASSIGN THE ADDRESS OF THE HEX COLOR OF THE IMAGE TO SI

MOV CX,word ptr Car2Position    ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON X AXIS OF THE CAR 
MOV DX,word ptr Car2Position+4  ;ASSIGN THE ADDRESS OF THE BEGINNING POSITION ON Y AXIS OF THE CAR 
BACK:
MOV AH,0DH
INT 10H
MOV [SI+540],AL
MOV AH,0CH
MOV AL,[SI]   ;COLOR OF THE PIXEL
INT 10H             ;Draw PixeL
INC CX              ;MOVE ON PIXEL ON X AXIS
INC SI              ;MOVE TO THE NEXT PIXEL COLOR
CMP CX,word ptr Car2Position+2      ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE X AXIS
JNZ BACK
MOV CX,WORD PTR Car2Position        ;RETURN TO THE BEGINNING POSITION ON X AXIS
DEC DX
CMP DX,WORD PTR Car2Position+6      ;CHECK IF I REACH THE END OF IMAGE'S RANGE ON THE Y AXIS
JNZ BACK

RET
VerCar2 ENDP
END VerCar2